name: Update Dependencies

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-flake:
    name: Update Nix Flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update flake inputs
      run: |
        nix flake update --commit-lock-file

    - name: Test updated flake
      run: |
        nix flake check --show-trace
        nix build .#swarmreport --print-build-logs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update Nix flake dependencies"
        title: "🔄 Update Nix flake dependencies"
        body: |
          ## 🔄 Automated Dependency Update
          
          This PR updates the Nix flake dependencies to their latest versions.
          
          ### Changes
          - Updated `flake.lock` with latest input versions
          - All builds and tests pass with updated dependencies
          
          ### Verification
          - ✅ Flake check passes
          - ✅ Build succeeds
          - ✅ All CI checks will run on this PR
          
          **Note**: This is an automated update. Please review the changes before merging.
        branch: update-deps/nix-flake
        delete-branch: true

  update-cargo:
    name: Update Cargo Dependencies  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update Cargo dependencies
      run: |
        nix develop --command cargo update

    - name: Test updated dependencies
      run: |
        nix develop --command cargo check
        nix develop --command cargo test
        nix develop --command cargo audit

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update Cargo dependencies"
        title: "📦 Update Cargo dependencies"
        body: |
          ## 📦 Automated Cargo Dependency Update
          
          This PR updates the Rust dependencies to their latest compatible versions.
          
          ### Changes
          - Updated `Cargo.lock` with latest dependency versions
          - All tests pass with updated dependencies
          - Security audit passes
          
          ### Verification
          - ✅ `cargo check` passes
          - ✅ `cargo test` passes  
          - ✅ `cargo audit` passes
          - ✅ All CI checks will run on this PR
          
          **Note**: This is an automated update. Please review the changes before merging.
        branch: update-deps/cargo
        delete-branch: true